import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({selector:'app-page-header',standalone:true,template:`<header class="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p class="eyebrow">Davao del Norte · threat intelligence</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-white sm:text-3xl">{{title}}</h1><p class="mt-2 text-sm text-slate-400">{{subtitle}}</p></div><button class="btn btn-secondary">Last 24 hours⌄</button></header>`})
export class PageHeaderComponent {@Input() title='';@Input() subtitle='';}

@Component({selector:'app-threat-chart',standalone:true,template:`<article class="cyber-card p-5"><div class="flex items-start justify-between"><div><h3 class="font-semibold text-white">{{title}}</h3><p class="mt-1 text-xs text-slate-500">Live community intelligence</p></div><span class="pill risk-info">Updated now</span></div><div class="chart-grid mt-6 h-48 overflow-hidden rounded-xl"><svg class="h-full w-full" viewBox="0 0 500 180" preserveAspectRatio="none"><path d="M0 148 C45 130 73 145 112 119 S180 137 221 88 S290 112 332 69 S408 94 500 22" fill="none" stroke="#22d3ee" stroke-width="3"/><path d="M0 148 C45 130 73 145 112 119 S180 137 221 88 S290 112 332 69 S408 94 500 22 V180 H0Z" fill="#22d3ee" opacity=".09"/></svg></div></article>`})
export class ThreatChartComponent {@Input() title='Threat trend';}

@Component({selector:'app-threat-map',standalone:true,template:`<div class="map-surface grid-bg"><div class="map-label">DAVAO DEL NORTE<br/><span>INCIDENT LAYER</span></div><div class="marker critical" style="left:25%;top:28%"><b>32</b><small>Tagum</small></div><div class="marker warning" style="left:51%;top:53%"><b>18</b><small>Panabo</small></div><div class="marker safe" style="left:72%;top:34%"><b>7</b><small>Samal</small></div><div class="map-water">DAVAO GULF</div></div>`})
export class ThreatMapComponent {}

@Component({selector:'app-report-table',standalone:true,imports:[CommonModule],template:`<article class="cyber-card overflow-hidden"><div class="flex items-center justify-between p-5"><div><h3 class="font-semibold text-white">Recent scam reports</h3><p class="mt-1 text-xs text-slate-500">Community-verified intelligence</p></div><span class="pill risk-info">148 total</span></div><div class="overflow-x-auto"><table class="w-full min-w-165 text-left text-sm"><thead><tr><th>Reporter</th><th>Municipality</th><th>Threat type</th><th>Status</th><th>Score</th></tr></thead><tbody>@for(r of rows;track r.name){<tr><td class="font-medium text-slate-200">{{r.name}}</td><td>{{r.city}}</td><td>{{r.type}}</td><td><span class="pill risk-info">{{r.status}}</span></td><td><span [class]="r.score>75?'pill risk-high':'pill risk-medium'">{{r.score}}</span></td></tr>}</tbody></table></div></article>`})
export class ReportTableComponent {rows=[{name:'Maria Reyes',city:'Tagum City',type:'GCash Phishing',score:91,status:'Investigating'},{name:'Jun Pangan',city:'Panabo City',type:'Fake Marketplace',score:72,status:'Open'},{name:'Anonymous',city:'Samal',type:'QR Scam',score:64,status:'Verified'},{name:'Rafael Dela Peña',city:'Carmen',type:'Fake Job Offer',score:58,status:'Open'}];}
