import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';

const reports = [{name:'Maria R.',city:'Tagum City',type:'GCash Phishing',score:91,status:'Investigating',date:'12 min ago'},{name:'Jun P.',city:'Panabo City',type:'Fake Marketplace',score:72,status:'Open',date:'28 min ago'},{name:'Anonymous',city:'Island Garden City of Samal',type:'QR Scam',score:64,status:'Verified',date:'1 hr ago'},{name:'Rafael D.',city:'Carmen',type:'Fake Job Offer',score:58,status:'Open',date:'2 hrs ago'}];
const municipal = [{name:'Tagum City',score:82,trend:'+12%'},{name:'Panabo City',score:68,trend:'+8%'},{name:'Samal',score:47,trend:'-4%'},{name:'Sto. Tomas',score:55,trend:'+5%'},{name:'Kapalong',score:39,trend:'-7%'},{name:'Carmen',score:61,trend:'+9%'}];
@Component({selector:'app-portal-page',standalone:true,imports:[CommonModule,RouterLink,DashboardComponent,WeatherComponent,HeatmapComponent,ScannerComponent,ReportsComponent,AlertsComponent,AnalyticsComponent,MunicipalitiesComponent,BarangaysComponent,GenericComponent],template:`
<section class="page-enter mx-auto max-w-7xl">@switch(kind){
 @case('dashboard'){<app-dashboard />}
 @case('weather'){<app-weather />}
 @case('heatmap'){<app-heatmap />}
 @case('scanner'){<app-scanner />}
 @case('reports'){<app-reports />}
 @case('alerts'){<app-alerts />}
 @case('analytics'){<app-analytics />}
 @case('municipalities'){<app-municipalities />}
 @case('barangays'){<app-barangays />}
 @default{<app-generic [kind]="kind" />}
}</section>`})
export class PortalPageComponent { route=inject(ActivatedRoute); kind=this.route.snapshot.data['kind'] || 'dashboard'; }

@Component({selector:'app-dashboard',standalone:true,imports:[CommonModule,RouterLink],template:`
<div class="mb-6 flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-cyan-400">Davao del Norte · Live intelligence</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-white sm:text-3xl">Good evening, Elton.</h1></div><span class="pill risk-low">● LIVE MONITORING</span></div>
<div class="cyber-card relative mb-6 overflow-hidden p-6 sm:p-8"><div class="absolute right-0 top-0 h-64 w-64 rounded-full bg-red-500/10 blur-3xl"></div><div class="relative grid gap-5 md:grid-cols-[1fr_auto]"><div><p class="text-sm text-slate-400">Community Cyber Threat Radar for Davao del Norte</p><h2 class="mt-3 max-w-xl text-2xl font-semibold tracking-tight text-white">A coordinated scam wave is affecting <span class="text-red-400">Tagum City</span>.</h2><p class="mt-3 max-w-lg text-sm leading-6 text-slate-400">Stay alert for GCash impersonation links shared through Facebook Marketplace and SMS.</p><div class="mt-5 flex flex-wrap gap-3"><a routerLink="/scanner" class="btn btn-primary">◉ Scan now</a><a routerLink="/reports" class="btn btn-secondary">+ Report scam</a></div></div><div class="rounded-2xl border border-red-400/25 bg-red-500/10 p-5 text-center"><p class="text-xs font-bold tracking-widest text-red-300">TODAY'S CYBER RISK</p><p class="mt-2 text-4xl font-black text-red-400">HIGH</p><p class="mt-2 text-xs text-slate-400">Tagum City · 82/100</p><span class="mt-4 inline-block h-3 w-3 rounded-full bg-red-400 pulse-soft"></span></div></div></div>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@for(s of stats;track s.label){<div class="cyber-card hover-lift p-5"><div class="flex justify-between"><span class="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/10 text-lg text-cyan-300">{{s.icon}}</span><span class="text-xs text-emerald-400">↗ {{s.delta}}</span></div><p class="mt-5 text-2xl font-bold text-white">{{s.value}}</p><p class="mt-1 text-xs text-slate-500">{{s.label}}</p><div class="mt-4 h-1 rounded bg-slate-800"><div class="h-1 rounded bg-cyan-400" [style.width]="s.bar"></div></div></div>}</div>
<div class="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><div class="cyber-card p-5"><div class="flex items-center justify-between"><div><h3 class="font-semibold text-white">Scam heatmap</h3><p class="mt-1 text-xs text-slate-500">Municipality incident concentration · last 24 hours</p></div><a routerLink="/heatmap" class="btn btn-secondary">View full map ↗</a></div><div class="grid-bg relative mt-5 h-72 overflow-hidden rounded-xl border border-slate-800 bg-[#081221]"><div class="absolute left-[17%] top-[24%] h-4 w-4 rounded-full bg-red-400 ring-8 ring-red-400/15"></div><div class="absolute left-[45%] top-[48%] h-4 w-4 rounded-full bg-amber-400 ring-8 ring-amber-400/15"></div><div class="absolute right-[22%] top-[35%] h-4 w-4 rounded-full bg-emerald-400 ring-8 ring-emerald-400/15"></div><p class="absolute bottom-4 left-4 text-xs font-semibold tracking-widest text-cyan-200/70">DAVAO DEL NORTE / THREAT GRID</p></div><div class="mt-3 flex gap-4 text-[11px] text-slate-500"><span>● <i class="text-emerald-400 not-italic">Low</i></span><span>● <i class="text-amber-400 not-italic">Elevated</i></span><span>● <i class="text-red-400 not-italic">Critical</i></span></div></div><div class="cyber-card p-5"><div class="flex justify-between"><div><h3 class="font-semibold text-white">Latest alerts</h3><p class="mt-1 text-xs text-slate-500">Priority incidents</p></div><a routerLink="/alerts" class="text-xs text-cyan-300">View all</a></div><div class="mt-4 space-y-3">@for(a of alerts;track a.title){<div class="rounded-xl border border-slate-800 bg-slate-950/35 p-3"><div class="flex justify-between gap-3"><span [class]="'pill '+a.level">{{a.severity}}</span><span class="text-[10px] text-slate-600">{{a.time}}</span></div><p class="mt-2 text-sm font-medium text-slate-200">{{a.title}}</p><p class="mt-1 text-xs text-slate-500">{{a.city}}</p></div>}</div></div></div>
<div class="mt-5 grid gap-5 xl:grid-cols-[1.35fr_1fr]"><div class="cyber-card p-5"><div class="flex justify-between"><div><h3 class="font-semibold text-white">Threat trend</h3><p class="mt-1 text-xs text-slate-500">Reported incidents · seven days</p></div><span class="pill risk-info">+18.4%</span></div><div class="chart-grid relative mt-6 h-48 overflow-hidden rounded-xl"><svg viewBox="0 0 600 190" class="h-full w-full" preserveAspectRatio="none"><path d="M0,160 C60,142 75,152 120,128 S195,134 235,98 S312,119 355,75 S420,105 460,52 S540,67 600,18" fill="none" stroke="#22d3ee" stroke-width="3"/><path d="M0,160 C60,142 75,152 120,128 S195,134 235,98 S312,119 355,75 S420,105 460,52 S540,67 600,18 V190 H0Z" fill="url(#g)" opacity=".2"/><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#22d3ee"/><stop offset="1" stop-color="#22d3ee" stop-opacity="0"/></linearGradient></defs></svg></div></div><app-report-table /></div>
`}) export class DashboardComponent {stats=[{label:'Threat score',value:'82',delta:'12%',icon:'◈',bar:'82%'},{label:'Reports today',value:'148',delta:'18%',icon:'▤',bar:'68%'},{label:'Active alerts',value:'24',delta:'6%',icon:'♧',bar:'45%'},{label:'Barangays affected',value:'37',delta:'9%',icon:'⌖',bar:'54%'}];alerts=[{severity:'CRITICAL',title:'GCash spoofing campaign detected',city:'Tagum City',time:'12m ago',level:'risk-high'},{severity:'HIGH',title:'Suspicious QR codes reported',city:'Panabo City',time:'28m ago',level:'risk-medium'},{severity:'ELEVATED',title:'Fake hiring page circulating',city:'Carmen',time:'1h ago',level:'risk-info'}]}

@Component({selector:'app-report-table',standalone:true,imports:[CommonModule],template:`<div class="cyber-card overflow-hidden"><div class="flex items-center justify-between p-5"><div><h3 class="font-semibold text-white">Recent scam reports</h3><p class="mt-1 text-xs text-slate-500">Community-verified intelligence</p></div><span class="pill risk-info">148 total</span></div><div class="overflow-x-auto"><table class="w-full min-w-140 text-left text-sm"><thead class="border-y border-slate-800 text-[10px] uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Reporter</th><th>Municipality</th><th>Threat type</th><th>Status</th><th class="px-5">Score</th></tr></thead><tbody>@for(r of rows;track r.name){<tr class="border-b border-slate-800/70 text-slate-300"><td class="px-5 py-4 font-medium">{{r.name}}</td><td>{{r.city}}</td><td>{{r.type}}</td><td><span class="pill risk-info">{{r.status}}</span></td><td class="px-5"><span class="pill" [class.risk-high]="r.score>75" [class.risk-medium]="r.score<=75">{{r.score}}</span></td></tr>}</tbody></table></div></div>`}) export class ReportTableComponent {rows=reports}

@Component({selector:'app-page-header',standalone:true,inputs:['title','subtitle'],template:`<div class="mb-6 flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-cyan-400">Threat intelligence</p><h1 class="mt-1 text-2xl font-bold text-white sm:text-3xl">{{title}}</h1><p class="mt-2 text-sm text-slate-400">{{subtitle}}</p></div><button class="btn btn-secondary">Today ⌄</button></div>`}) export class PageHeaderComponent {title='';subtitle=''}
@Component({selector:'app-chart-card',standalone:true,inputs:['title'],template:`<div class="cyber-card p-5"><h3 class="font-semibold text-white">{{title}}</h3><div class="chart-grid mt-5 h-44 rounded-xl"><svg class="h-full w-full" viewBox="0 0 500 180" preserveAspectRatio="none"><path d="M0 145 C60 95,100 150,150 105 S230 125,290 70 S390 95,500 25" fill="none" stroke="#22d3ee" stroke-width="3"/></svg></div></div>`}) export class ChartCardComponent {title=''}
@Component({selector:'app-weather',standalone:true,imports:[CommonModule,PageHeaderComponent,ChartCardComponent],template:`<app-page-header title="Cyber Weather Forecast" subtitle="A localized risk forecast for the Davao del Norte community." /><div class="cyber-card mb-6 flex flex-wrap items-center justify-between gap-4 border-amber-400/30 p-6"><div><span class="pill risk-medium">ELEVATED RISK</span><h2 class="mt-3 text-2xl font-bold text-white">Prepare for credential theft attempts.</h2><p class="mt-2 text-sm text-slate-400">Forecasted peak: 7:00 PM - 10:00 PM today</p></div><div class="text-5xl text-amber-400">◌</div></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@for(m of cities;track m.name){<div class="cyber-card p-5"><div class="flex justify-between"><p class="font-semibold text-white">{{m.name}}</p><span [class]="'pill '+risk(m.score)">{{m.score>70?'HIGH':m.score>50?'ELEVATED':'GUARDED'}}</span></div><p class="mt-5 text-3xl font-bold text-white">{{m.score}}<span class="text-sm text-slate-500">/100</span></p><p class="mt-2 text-xs text-emerald-400">{{m.trend}} compared with yesterday</p><div class="mt-4 h-1.5 rounded-full bg-slate-800"><div class="h-full rounded-full bg-cyan-400" [style.width.%]="m.score"></div></div></div>}</div><div class="mt-6 grid gap-5 lg:grid-cols-2"><app-chart-card title="Threat forecast timeline"/><app-chart-card title="Top scam categories"/></div></template>`}) export class WeatherComponent {cities=municipal;risk=(n:number)=>n>70?'risk-high':n>50?'risk-medium':'risk-low'}
@Component({selector:'app-heatmap',standalone:true,imports:[PageHeaderComponent],template:`<app-page-header title="Scam Heatmap" subtitle="Live community threat concentration across Davao del Norte." /><div class="mb-5 flex flex-wrap gap-2"><button class="btn btn-secondary">All municipalities⌄</button><button class="btn btn-secondary">All threat types⌄</button><button class="btn btn-secondary">Last 24 hours⌄</button><button class="btn btn-primary">◉ Live feed</button></div><div class="grid gap-5 xl:grid-cols-[1fr_310px]"><div class="cyber-card grid-bg relative min-h-125 overflow-hidden p-5"><div class="absolute left-[18%] top-[25%] h-5 w-5 rounded-full bg-red-400 ring-12 ring-red-400/15"></div><div class="absolute left-[48%] top-[47%] h-4 w-4 rounded-full bg-amber-400 ring-10 ring-amber-400/15"></div><div class="absolute right-[20%] top-[30%] h-4 w-4 rounded-full bg-emerald-400 ring-10 ring-emerald-400/15"></div><div class="absolute bottom-5 left-5 rounded-lg bg-slate-950/85 px-3 py-2 text-xs tracking-wider text-cyan-200">DAVAO DEL NORTE · INCIDENT LAYER</div></div><div class="space-y-4"><div class="cyber-card p-5"><h3 class="font-semibold text-white">Threat legend</h3><div class="mt-4 space-y-3 text-sm text-slate-400"><p>● <span class="ml-2 text-emerald-400">Low intensity</span></p><p>● <span class="ml-2 text-amber-400">Elevated activity</span></p><p>● <span class="ml-2 text-red-400">Critical outbreak</span></p></div></div><div class="cyber-card p-5"><h3 class="font-semibold text-white">Top affected barangays</h3><ol class="mt-4 space-y-3 text-sm text-slate-400"><li>01. Magugpo East <b class="float-right text-red-300">24</b></li><li>02. San Francisco <b class="float-right text-amber-300">18</b></li><li>03. Mankilam <b class="float-right text-amber-300">15</b></li></ol></div></div></div></template>`}) export class HeatmapComponent {}
