import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthService } from '../../core/api/auth.service';

@Component({
  selector: 'app-auth-page', standalone: true, imports: [FormsModule, RouterLink],
  template: `<main class="auth-screen grid-bg"><section class="auth-card page-enter">
  <a routerLink="/dashboard" class="mb-8 flex items-center justify-center gap-3 text-xl font-bold text-white"><span class="icon-box">◈</span>Davnor<span class="text-cyan-300">Shield</span></a>
  @if (mode === 'login') { <p class="eyebrow">Secure access</p><h1 class="mt-2 text-2xl font-bold text-white">Welcome back.</h1><p class="mt-2 text-sm text-slate-400">Sign in to your community cyber radar.</p><form class="mt-7 space-y-4" (ngSubmit)="login()"><label class="block text-sm text-slate-300">Email<input class="input mt-2" name="email" type="email" [(ngModel)]="email" required /></label><label class="block text-sm text-slate-300">Password<input class="input mt-2" name="password" type="password" [(ngModel)]="password" minlength="8" required /></label><p class="rounded bg-emerald-500/15 p-3 text-sm text-emerald-300" [hidden]="!success" role="status">{{ success }}</p><p class="rounded bg-red-500/15 p-3 text-sm text-red-300" [hidden]="!error" role="alert">{{ error }}</p><button class="btn btn-primary w-full py-3" type="submit" [disabled]="busy">{{ busy ? 'Signing in…' : 'Sign in to DavnorShield →' }}</button></form><p class="mt-6 text-center text-sm text-slate-500">New to DavnorShield? <a routerLink="/register" class="text-cyan-300">Create an account</a></p> }
  @else { <p class="eyebrow">Join the network</p><h1 class="mt-2 text-2xl font-bold text-white">Create your account.</h1><p class="mt-2 text-sm text-slate-400">Help make Davao del Norte safer online.</p><form class="mt-7 grid gap-4" (ngSubmit)="register()"><label class="block text-sm text-slate-300">Full name<input class="input mt-2" name="fullName" [(ngModel)]="fullName" required /></label><label class="block text-sm text-slate-300">Email<input class="input mt-2" name="regEmail" type="email" [(ngModel)]="email" required /></label><label class="block text-sm text-slate-300">Password<input class="input mt-2" name="regPassword" type="password" [(ngModel)]="password" minlength="8" required /></label><label class="block text-sm text-slate-300">Confirm password<input class="input mt-2" name="confirmPassword" type="password" [(ngModel)]="confirmPassword" minlength="8" required /></label><p class="rounded bg-emerald-500/15 p-3 text-sm text-emerald-300" [hidden]="!success" role="status">{{ success }}</p><p class="rounded bg-red-500/15 p-3 text-sm text-red-300" [hidden]="!error" role="alert">{{ error }}</p><button class="btn btn-primary w-full py-3" type="submit" [disabled]="busy">{{ busy ? 'Creating account…' : 'Create secure account →' }}</button></form><p class="mt-6 text-center text-sm text-slate-500">Already protected? <a routerLink="/login" class="text-cyan-300">Sign in</a></p> }
</section></main>`
})
export class AuthPageComponent {
  private readonly route = inject(ActivatedRoute); private readonly auth = inject(AuthService); private readonly router = inject(Router);
  mode = this.route.snapshot.data['mode']; email = ''; password = ''; confirmPassword = ''; fullName = ''; busy = false; error = ''; success = '';
  login(): void { if (!this.validCredentials()) return; this.busy = true; this.clearNotices(); this.auth.login({ email: this.email, password: this.password }).pipe(finalize(() => this.busy = false)).subscribe({ next: () => this.finish('Signed in successfully. Redirecting to your dashboard…'), error: e => this.fail(e) }); }
  register(): void { if (!this.fullName.trim()) { this.error = 'Please enter your full name.'; return; } if (!this.validCredentials() || this.password !== this.confirmPassword) { if (!this.error) this.error = 'Passwords do not match.'; return; } this.busy = true; this.clearNotices(); this.auth.register({ full_name: this.fullName.trim(), email: this.email, password: this.password, role: 'citizen', is_active: true }).pipe(finalize(() => this.busy = false)).subscribe({ next: () => this.finish('Account created successfully. Redirecting to your dashboard…'), error: e => this.fail(e) }); }
  private validCredentials(): boolean { this.clearNotices(); if (!/^\S+@\S+\.\S+$/.test(this.email)) { this.error = 'Enter a valid email address.'; return false; } if (this.password.length < 8) { this.error = 'Password must be at least 8 characters.'; return false; } return true; }
  private clearNotices(): void { this.error = ''; this.success = ''; }
  private finish(message: string): void { this.busy = false; this.success = message; window.setTimeout(() => void this.router.navigate(['/dashboard']), 900); }
  private fail(error: { detail?: unknown; message?: string }): void { const detail = (error.detail as { detail?: unknown } | undefined)?.detail; this.error = Array.isArray(detail) ? detail.map((item: { msg?: string }) => item.msg).filter(Boolean).join(' ') : typeof detail === 'string' ? detail : error.message || 'Unable to complete the request.'; }
}
