import { Component, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';

@Component({selector:'app-auth-page',standalone:true,imports:[RouterLink],template:`
<main class="auth-screen grid-bg"><div class="auth-glow one"></div><div class="auth-glow two"></div><section class="auth-card page-enter">
  <a routerLink="/dashboard" class="mb-8 flex items-center justify-center gap-3 text-xl font-bold text-white"><span class="icon-box">◈</span>Davnor<span class="text-cyan-300">Shield</span></a>
  @if(mode==='login') {<div><p class="eyebrow">Secure access</p><h1 class="mt-2 text-2xl font-bold text-white">Welcome back.</h1><p class="mt-2 text-sm text-slate-400">Sign in to your community cyber radar.</p></div>
  <form class="mt-7 space-y-4"><label class="block text-sm text-slate-300">Email<input class="input mt-2" type="email" placeholder="you@example.com"/></label><label class="block text-sm text-slate-300">Password<input class="input mt-2" type="password" placeholder="••••••••"/></label><div class="flex justify-between text-xs"><label class="text-slate-400"><input type="checkbox" class="mr-2 accent-cyan-400"/>Remember me</label><a href="#" class="text-cyan-300">Forgot password?</a></div><a routerLink="/dashboard" class="btn btn-primary w-full py-3">Sign in to DavnorShield →</a></form><p class="mt-6 text-center text-sm text-slate-500">New to DavnorShield? <a routerLink="/register" class="text-cyan-300">Create an account</a></p>}
  @else {<div><p class="eyebrow">Join the network</p><h1 class="mt-2 text-2xl font-bold text-white">Create your account.</h1><p class="mt-2 text-sm text-slate-400">Help make Davao del Norte safer online.</p></div>
  <form class="mt-7 grid gap-4 sm:grid-cols-2"><label class="block text-sm text-slate-300 sm:col-span-2">Full name<input class="input mt-2" placeholder="Elton Dela Cruz"/></label><label class="block text-sm text-slate-300 sm:col-span-2">Email<input class="input mt-2" type="email" placeholder="you@example.com"/></label><label class="block text-sm text-slate-300">Municipality<select class="input mt-2"><option>Tagum City</option><option>Panabo City</option><option>Samal</option></select></label><label class="block text-sm text-slate-300">Barangay<select class="input mt-2"><option>Magugpo East</option><option>Mankilam</option></select></label><label class="block text-sm text-slate-300">Password<input class="input mt-2" type="password" placeholder="••••••••"/></label><label class="block text-sm text-slate-300">Confirm password<input class="input mt-2" type="password" placeholder="••••••••"/></label><label class="text-xs text-slate-400 sm:col-span-2"><input type="checkbox" class="mr-2 accent-cyan-400"/>I agree to the community safety guidelines and privacy policy.</label><a routerLink="/dashboard" class="btn btn-primary w-full py-3 sm:col-span-2">Create secure account →</a></form><p class="mt-6 text-center text-sm text-slate-500">Already protected? <a routerLink="/login" class="text-cyan-300">Sign in</a></p>}
</section></main>`})
export class AuthPageComponent { private route=inject(ActivatedRoute);mode=this.route.snapshot.data['mode'];}
